# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    environment:
      - CODECOV_TOKEN: "fafb9fb4-511d-4847-a653-5e7080f8b64a"
    steps:
      - codecov/upload:
          flags: unittests
        
    # Specify the Xcode version to use
    macos:
      xcode: "11.0.0"
    
    steps:
      - checkout

      # Install CocoaPods
      #- run:
      #    name: Install CocoaPods
      #    command: pod install

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8 (13.0)
            SCAN_SCHEME: Hover

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs